[package]
name = "sudoku_solver_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
indoc = "2.0.5"
itertools = "0.14.0"
strum = "0.26.3"
strum_macros = "0.26.4"
